name = "Pretty"
uuid = "f176f2d6-f546-4398-8099-07d77d4d3304"
authors = ["Chris DeGrendele <christopher.degrendele@stonybrook.edu>"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
